version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  hivemq:
    image: hivemq/hivemq4
    ports:
      - "1883:1883" # MQTT port
      - "8000:8000" # Web UI port (optional)

volumes:
  rabbitmq_data:
